### ISSUE TITLE
Failure to parse some CBF's

### ISSUE THREAD

**Issue by prj** [jglim/CaesarSuite#57]
For example ME28.cbf.

Bunch of errors like this:
```
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_12
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_10
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_10
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_11
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_16
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_16
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_16
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_16
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_16
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_16
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_16
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_16
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_16
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_11
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_10
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_10
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_11
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_11
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_10
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_10
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_10
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_14
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_14
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_5E
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_11
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_58
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_12
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_58
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_12
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_11
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_11
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_12
Parsing experimental 0x410 prep with sysparam 17 at #0
0x410 : sys param: 17 for qualifier #0 could not find referenced DiagService with index DT_IOLID_10
```

Followed by this:
```
System.IO.IOException
  HResult=0x80131620
  Message=An attempt was made to move the position before the beginning of the stream.
  Source=mscorlib
  StackTrace:
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at Caesar.CaesarReader.ReadBitflagDumpWithReader(UInt64& bitFlags, BinaryReader reader, Int32 dumpSize, Int64 virtualBase) in C:\Tuning\Tools\repos\CaesarSuite\Caesar\Caesar\CaesarReader.cs:line 45
   at Caesar.ECUVariantPattern..ctor(BinaryReader reader, Int64 baseAddress) in C:\Tuning\Tools\repos\CaesarSuite\Caesar\Caesar\ECUVariantPattern.cs:line 82
   at Caesar.ECUVariant.CreateVariantPatterns(BinaryReader reader) in C:\Tuning\Tools\repos\CaesarSuite\Caesar\Caesar\ECUVariant.cs:line 247
   at Caesar.ECUVariant..ctor(BinaryReader reader, ECU parentEcu, CTFLanguage language, Int64 baseAddress, Int32 blockSize) in C:\Tuning\Tools\repos\CaesarSuite\Caesar\Caesar\ECUVariant.cs:line 171
   at Caesar.ECU.CreateEcuVariants(BinaryReader reader, CTFLanguage language) in C:\Tuning\Tools\repos\CaesarSuite\Caesar\Caesar\ECU.cs:line 543
   at Caesar.ECU..ctor(BinaryReader reader, CTFLanguage language, CFFHeader header, Int64 baseAddress, CaesarContainer parentContainer) in C:\Tuning\Tools\repos\CaesarSuite\Caesar\Caesar\ECU.cs:line 367
   at Caesar.CaesarContainer.ReadECU(BinaryReader fileReader) in C:\Tuning\Tools\repos\CaesarSuite\Caesar\Caesar\CaesarContainer.cs:line 204
   at Caesar.CaesarContainer..ctor(Byte[] fileBytes) in C:\Tuning\Tools\repos\CaesarSuite\Caesar\Caesar\CaesarContainer.cs:line 49
   at Caesar.Program.Main(String[] args) in C:\Tuning\Tools\repos\CaesarSuite\Caesar\Caesar\Program.cs:line 17

  This exception was originally thrown at this call stack:
    [External Code]
    Caesar.CaesarReader.ReadBitflagDumpWithReader(ref ulong, System.IO.BinaryReader, int, long) in CaesarReader.cs
    Caesar.ECUVariantPattern.ECUVariantPattern(System.IO.BinaryReader, long) in ECUVariantPattern.cs
    Caesar.ECUVariant.CreateVariantPatterns(System.IO.BinaryReader) in ECUVariant.cs
    Caesar.ECUVariant.ECUVariant(System.IO.BinaryReader, Caesar.ECU, Caesar.CTFLanguage, long, int) in ECUVariant.cs
    Caesar.ECU.CreateEcuVariants(System.IO.BinaryReader, Caesar.CTFLanguage) in ECU.cs
    Caesar.ECU.ECU(System.IO.BinaryReader, Caesar.CTFLanguage, Caesar.CFFHeader, long, Caesar.CaesarContainer) in ECU.cs
    Caesar.CaesarContainer.ReadECU(System.IO.BinaryReader) in CaesarContainer.cs
    Caesar.CaesarContainer.CaesarContainer(byte[]) in CaesarContainer.cs
    Caesar.Program.Main(string[]) in Program.cs
```

This is an older controller, that is on K-Line, not on CAN.
But then for example CR2 and CR3 parse just fine.

**Comment by prj** [comment]
Seems like only the Unk16 field fails.
I did this in CaesarReader.ReadBitFlagDumpWithHeader and it seems that everything else gets parsed okay I think... The readout "offset" is a huge int value. I wonder if in this cbf it's a direct value and not an offset at all actually.
```
try {
    // seek to the specified offset, then read out the dump
    reader.BaseStream.Seek(dumpOffset + virtualBase, SeekOrigin.Begin);
    result = reader.ReadBytes(dumpSize);
    // restore our reading cursor
} catch (IOException) {
    Console.WriteLine("Failed to read BitflagDump!");
    result = new byte[] { };
}
```

**Comment by prj** [comment]
So the offset is always screwed. It's way higher than the file size. The reason it fails on this one, is because you're using an int and it rolls over and becomes negative.
I wonder if all the offsets are actually 24 bit. And then the MSB is used for some kind of flags.
It always seems to be 0x32 here.

Either that or the format/order is just different in this.

**Comment by prj** [comment]
Mystery solved. This field is just the first 4 bytes of the IDENT request. If it's present then that's what should be used as ident.
It's deffo not a pointer to somewhere.

Comms log:
```
[>] 82 10 F1 1A 86 23
[<] 92 F1 10 5A 86 11 21 53 26 79 08 01 37 01 03 01 05 00 15 02 02 FA
````
And from the previous list there is 26532111 in there.

The logic is check is basically, check if both vendor id and this byte array match, and if not just match the byte array to get the variant.

**Comment by jglim** [comment]
Nice to see you again prj, and thanks for investigating and solving this mystery. Looking forward to your PR!

**Comment by prj** [comment]
I made it a byte array, because it is literally the first byte ofs a 1A 86 ident. Converting it to an uint or some other datatype does not make sense, as it creates unnecessary endianness issues.

**Comment by jglim** [comment]
Byte array is a good fit. I might tweak the names slightly in the future as that value appears to be specific to KWP2000. 

Thanks again for your contribution!

**Comment by prj** [comment]
Yeah, I don't really know what to name it.
Maybe EcuId1A86 did not seem to be much better.

It can be present only in KWP2000PE/KWP20C3PE controllers and those that use the longer 1A 86 for identification, not 1A 87.
